#!/bin/bash
export LANG='en_US.UTF-8'

color_primary="38;5;45"
color_secondary="38;5;93"

paste <(/etc/update-motd.d/scripts/falcon-header && /etc/update-motd.d/scripts/ups-status) <(. /etc/update-motd.d/scripts/zfs/zpool-bar) | column -s $'\t' -tn

echo ""

paste <(/etc/update-motd.d/scripts/ssl) <(/etc/update-motd.d/scripts/services) | column -s $'\t' -tn
