#!/bin/bash
export LANG='en_US.UTF-8'

# Stealing this naming scheme from bootstrap
color_primary="38;5;45"
color_secondary="38;5;68"
color_danger="38;5;1"
color_warning="38;5;11"
color_success="38;5;2"

# Domains for SSL certificate module
module_ssl_domains="google.com wikipedia.org"

paste <(. /etc/update-motd.d/scripts/header/falcon-header && . /etc/update-motd.d/scripts/ups-status) <(. /etc/update-motd.d/scripts/zfs/zpool-bar) | column -s $'\t' -tn

echo ""

paste <(. /etc/update-motd.d/scripts/ssl) <(. /etc/update-motd.d/scripts/services) | column -s $'\t' -tn

echo ""

# Configure your own list of /dev/* values, sda, sdb, sdc...
mapfile -t disks < <(blkid | grep 'LABEL="storage"\|LABEL="haverchuck"' | sed -r 's/^\/dev\/([a-z]{3}).*$/\1/')

paste <(. /etc/update-motd.d/scripts/disktemp)

# Dont know what im doing with this yet
# echo -e "$(gcal -H '\e[46;30m:\e[0m:\e[45m:\e[0m' -q IS)"
