#!/bin/bash

# config
max_usage=90
bar_width=32

# colors
color_red="38;5;160"
color_unused=${color_secondary:="35"}
color_used=${color_primary:="36"}
color_primary=${color_primary:="36"}

# zpool usage
mapfile -t zpools < <(zpool list -Ho name,cap,size)
echo -e "\e[${color_primary}mDisk usage:\e[0m"

for line in "${zpools[@]}"; do

    # Get the zpool percentage of space used
    usage=$(echo "$line" | awk '{print $2}' | sed 's/%//')

    # Get the whole number from 0 to bar width of used space
    used_width=$((($usage*$bar_width)/100))

    # color is color_used if usage < max_usage, else red
    if [ "${usage}" -ge "${max_usage}" ]; then
        color=$color_red
    else
        color=$color_used
    fi

    # print green/red bar until used_width
    bar="[\e[${color}m"
    for ((i=0; i<$used_width; i++)); do
        bar+="="
    done

    # print dimmmed bar until end
    bar+="\e[2;${color_unused}m"
    for ((i=$used_width; i<$bar_width; i++)); do
        bar+="="
    done
    bar+="\e[0m]"
    # print usage line & bar
    echo "${line}" | awk '{ printf("%-18s%+3s out of %+5s\n", $1, $2, $3); }' | sed -e 's/^//'
    echo -e "${bar}" | sed -e 's/^//'
done

