#!/bin/bash

color=${color_primary:="36"}

echo -e "\e[${color}m   _______   __   _________  _  __\e[0m
\e[${color}m  / __/ _ | / /  / ___/ __ \/ |/ /\e[0m
\e[${color}m / _// __ |/ /__/ /__/ /_/ /    / \e[0m
\e[${color}m/_/ /_/ |_/____/\___/\____/_/|_/  \e[0m"
