#!/bin/bash
export LANG='en_US.UTF-8'

# Declare array of services and pretty human readable names
declare -a services=(
"smbd"
"plexmediaserver"
"fail2ban"
"apcupsd"
"ufw"
)
declare -a serviceName=(
"Samba"
"Plex"
"Fail2Ban"
"APC UPS Daemon"
"UFW"
)
declare -a serviceStatus=()

# Get status of all my services
for service in "${services[@]}"
do
    serviceStatus+=($(systemctl is-active "$service.service"))
done

# Maximum column width
#width=$((49-2))
width=$((34))

# Current line and line length
line=""
lineLen=0

echo "Services running:"

for i in ${!serviceStatus[@]}
do
    # Next line and next line length
    next="  ${serviceName[$i]}"
    nextLen=$((1+${#next}))

    # If the current line will exceed the max column with then echo the current line and start a new line
    if [[ $((lineLen+nextLen)) -gt width ]]; then
    echo -e "$line"
    lineLen=0
    line=""
    fi

    lineLen=$((lineLen+nextLen))

    # Color the next line green if it's active, else red
    if [[ "${serviceStatus[$i]}" == "active" ]]; then
    line+="\e[36m● ${serviceName[$i]}\e[0m "
    else
    line+="\e[1;33m▲ ${serviceName[$i]}\e[0m "
    fi
done

# echo what is left
echo -e "$line"

