#!/bin/bash
export LANG='en_US.UTF-8'

ssl_domains="hermann.is skolakerfi.is"
currentTime=$(date +%s)
output="TLS certs|      Valid until"

for domain in $ssl_domains; do
    certTime=$(openssl s_client -servername ${domain} -connect ${domain}:443 < /dev/null 2>/dev/null | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2)
    certLineTime=$(date -d "${certTime}" +"%a %b %d %Y")

    certTimestamp=$(date -d "${certTime}" +%s)
    if [ "${certTimestamp}" -ge "${currentTime}" ]; then
        sign="\e[36m●\e[0m"
    else
        sign="\e[1;33m▲\e[0m"
    fi

    output+="\n$sign $domain|  $certLineTime"
done

echo -e "$output" | column -t -s '|'
